### ISSUE TITLE
Short ATR_TRAILING Model

### ISSUE THREAD

**Issue by AlphaNumeriq123** [Pure-Alpha-Ventures-FZ-LLC/Backtester#3]
ATR_TRAILING model for short atr value is not there
![atr value](https://github.com/Pure-Alpha-Ventures-FZ-LLC/Backtester/assets/160572085/be50fc81-889e-40ea-9288-6c9bb251e2f3)

**Comment by AlphaNumeriq123** [comment]
> Just to clarify, the atr value is not being logged in logs?

yes

**Comment by chiranjivsethi** [comment]
Fixed, Git pull from main.

**Comment by AlphaNumeriq123** [comment]
![Screenshot 2024-02-26 18362445](https://github.com/Pure-Alpha-Ventures-FZ-LLC/Backtester/assets/160572085/e6adaec7-104b-4a86-babf-38e9060a1c88)
For fixed trailing in short lot size calculation is wrong
